# https://www.datacamp.com/community/tutorials/bootstrap-r

library(boot)

foo <- function(data, indices, cor.type){
    dt<-data[indices,]
    c(
        cor(dt[,1], dt[,2], method=cor.type),
        median(dt[,1]),
        median(dt[,2])
    )
}
set.seed(12345)
myBootstrap <- boot(iris, foo, R=1000, cor.type='s')

myBootstrap

# As a result, we'll get R values of our statistic: T1, T2, …, TR.
# We call them bootstrap realizations of T or a bootstrap distribution of T.
# Based on it, we can calculate CI for T.
#There are several ways of doing this. Taking percentiles seems to be the easiest one.

#$t contains R values of our statistic(s) generated by the bootstrap procedure (bootstrap realizations of T)
head(myBootstrap$t)

#$t0 contains values of our statistic(s) in original, full, dataset:
myBootstrap$t0

# "actual" values from original sample, same as t0
cor(iris[,1], iris[,2], method='s')
median(iris[,1])
median(iris[,2])

myBootstrap

# bias is a difference between the mean of bootstrap realizations (those from $t), 
# called a bootstrap estimate of T and value in original dataset (the one from $t0).
colMeans(myBootstrap$t)-myBootstrap$t0

#std. error is a standard error of bootstrap estimate,
#which equals standard deviation of bootstrap realizations.
apply(myBootstrap$t, 2, sd)

# median(myBootstrap$t[,1])
# quantile(myBootstrap$t[,1], probs = 0.5)
# median(myBootstrap$t[,2])
# median(myBootstrap$t[,3])

plot(myBootstrap, index=1)
quantile(myBootstrap$t[,1], probs = c(0.025, 0.5, 0.975))

# normal CI
# typically would just be
# t0 ± z⋅se
# but in bootstrap case, we should correct it for bias. So it becomes:
# t0−b±zα⋅se
# 2t0−t⋆±zα⋅se
boot.ci(myBootstrap, index=1, type = c("norm", "perc", "basic"))
#Percentile CI is generally not recommended because it performs poorly 
# when it comes to weird-tailed distributions.
# Basic CI (also called pivotal or empirical CI) is much more robust to this.
#The rationale behind it is to compute differences between each bootstrap
# replication and t0 and use percentiles of their distribution.


plot(myBootstrap, index=2)
quantile(myBootstrap$t[,2], probs = c(0.025, 0.5, 0.975))

plot(myBootstrap, index=3)
quantile(myBootstrap$t[,3], probs = c(0.025, 0.5, 0.975))












